from typing import Optional

ALGORITHMS: tuple[str, ...]
WEIGHTS: tuple[str, ...]

class Move:
    dir: int
    id: int
    cell: int
    def __init__(self, dir: int = ..., id: int = ..., cell: int = ...) -> None: ...
    def key(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Board:
    p0: int
    p1: int
    def __init__(self, p0: int = ..., p1: int = ...) -> None: ...
    @staticmethod
    def classical() -> Board: ...
    def copy(self) -> Board: ...
    def is_legal(self, move: Move, player: int) -> bool: ...
    def legal_moves(self, player: int) -> list[Move]: ...
    def apply(self, move: Move, player: int) -> None: ...
    def evaluate(self, weights: str = "default") -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Solver:
    def __init__(
        self,
        algo: str = "abtt",
        depth: Optional[int] = None,
        weights: str = "default",
        quiescent: bool = False,
        window: int = 1000,
        tt_mb: int = 64,
        budget_ms: int = 0,
    ) -> None: ...
    def best_move(self, board: Board, player: int) -> Optional[Move]: ...
    @property
    def depth(self) -> int: ...
    @property
    def budget_ms(self) -> int: ...
    @property
    def nodes(self) -> int: ...
    @property
    def leaves(self) -> int: ...
    @property
    def last_depth(self) -> int: ...
    @property
    def last_score(self) -> int: ...

def parse_atp(board: Board, player: int, move: str) -> Optional[Move]: ...
def move_to_atp(board: Board, player: int, move: Move) -> str: ...
def cell_name(cell: int) -> str: ...
def cell_from_name(name: str) -> int: ...
def perft(board: Board, depth: int, player: int) -> int: ...
